package util;

import java.io.IOException;

public abstract class Parser {
    public Dictionary dict = null;

    public Parser(Configure conf) throws IOException{
	dict = new Dictionary(conf);
    }
    
    
    /*
     * stem a word into basic form, e.g., did-> do
     * 
     * @param word	input word
     * @return	the stemmed wrod
     */
    public abstract String stemWord(String word);
    
    
    /*
     * split input string into a set of tokens.
     * 
     * @param text 	a string
     * @return 	a set of string tokens
     */
    public abstract String[] tokenize(String text);
    
    
    /*
     * parse raw document(from document collection) to remove 
     * unnecessary fields. it is used by {@link Converter} 
     * 
     * @param doc raw document encoded(e.g., json) as a string 
     * @return	a parsed Document instance(unncessary fileds are removed)
     */
    public abstract Document parseRawDocument(String doc);
    
    
    /*
     * parse document, especially its text into vector model
     * 
     * @param doc a document encoded(e.g., json) as a string
     * which can be generated by {@link Converter} or {@link Crawler}
     * 
     * @return a parsed Document instance(text are represented using vector model)
     */
    public abstract Document parseDocument(String doc);
    
    
    public abstract void saveDictionary();
    
    
    public abstract void loadDictionary() throws IOException;
}
